### PR TITLE
Added filePasteTarget plugin and updated documentation

### PR DESCRIPTION
**Pull request by priyankjalu89**
- [x] Does each function have a comment to describe what it does ?
- [x] Are there comments throughout the code ?
- [x] Is each function unit testable ?
- [x] Are the function or method names well chosen ?
- [x] Are variable names well chosen ?
- [x] List what testing has been done.
- [x] UI changes - code reviewer should see changes.

### CODE REVIEW

**Comment by PeterChaplin** [comment]
Is there a browser / OS combination that allows pasting non-image files?

**Comment by PeterChaplin** [comment]
As far as I'm aware, no browser/OS combination supports pasting non-image files at this time. This would mean `filePasteTarget` is a redundant duplicate of `imagePasteTarget`, and should be dropped.

Please could you update accordingly.

**Comment by priyankjalu89** [comment]
I did have a look and found that pasting is not supported for non-image file. Updated the file accordingly based on Peter's suggestion.

**Comment by bvw** [comment]
Please tag and make new release.

**Pull request merged**
