### PR TITLE
Validation Plugin Docs

### PR DESCRIPTION
**Pull request by nicky-johnstone**
@bvw I've enhanced Priyank's version of the documentation. Let me know what you think.

I've not included it anywhere in the indexes as I believe Peter is still organising it all so I'll leave it to him to place appropriately.

### CODE REVIEW

**Comment by bvw** [comment]
Thanks Nicky, Do you have a codepen to link to which shows a working demo ?
Think @priyankjalu89  might have one ?

**Comment by nicky-johnstone** [comment]
Ah, right, I meant to include the two codepens that Priyank made. I'll get those added and will let you know when the document has been updated.

**Comment by nicky-johnstone** [comment]
Updated to include a section for usage examples with the two codepens Priyank has created.

**Comment by bvw** [comment]
Could you please link from this file
https://github.com/qcode-software/qcode-ui/blob/master/docs/forms/validation/index.md

**Pull request merged**
