### PR TITLE
Context menu

### PR DESCRIPTION
**Pull request by PeterChaplin**
JavaScript
-------------
- [x] Does each function have a comment to describe what it does ?
- [x] Are there comments throughout the code ?
- [x] Is each function unit testable ?
- [x] Are the function or method names well chosen ?
- [x] Are variable names well chosen ?

- [x] List what testing has been done.
- [x] UI changes - code reviewer should see changes.

### CODE REVIEW

**Comment by PeterChaplin** [comment]
Testing
----
- Used on mla-erp DEV to add a custom context menu for tables
- Opened menu
- Clicked outside menu to close
- Right-clicked elsewhere to close and re-open
- Scrolled page to close
- Used arrow keys to navigate menu items
- Clicked menu item to run function and close

**Comment by PeterChaplin** [comment]
image

**Comment by PeterChaplin** [comment]
Ready for review

**Comment by bvw** [comment]
Could we mimic the slightly lighter shade of blue used on Windows 

image

**Comment by PeterChaplin** [comment]
Done

**Comment by PeterChaplin** [comment]
image

**Pull request merged**
