### PR TITLE
Updated tableRowHighlight plugin

### PR DESCRIPTION
**Pull request by priyankjalu89**
Updated tableRowHighlight plugin

### CODE REVIEW

**Comment by priyankjalu89** [comment]
- [ ] Does each function have a comment to describe what it does ?
- [ ] Are there comments throughout the code ?
- [ ] Is each function unit testable ?
- [ ] Are the function or method names well chosen ?
- [ ] Are variable names well chosen ?
- [ ] List what testing has been done.
- [ ] UI changes - code reviewer should see changes.

**Comment by priyankjalu89** [comment]
UI testing 
1. Highlight row: click event on any cell of table
2. Un-Highlight row which is already highlighted: click event on any cell of the highlighted row

**Comment by bvw** [comment]
Event  `$(event.target).trigger('toggleHighlight');` is dropped as we cannot find anywhere that uses the event.

**Comment by PeterChaplin** [comment]
@bvw please could we arrange a phone call to discuss?

**Comment by PeterChaplin** [comment]
Could you please re-write this as a core jQuery plugin? I don't think we need the additional complexity of a jQuery UI widget in this case.
http://learn.jquery.com/plugins/basic-plugin-creation/

**Comment by priyankjalu89** [comment]
@PeterChaplin Redefined tableRowHighlight as a core jQuery plugin

**Comment by PeterChaplin** [comment]
Looks good to me.

**Pull request merged**
