### PR TITLE
Db form json

### PR DESCRIPTION
**Pull request by nicky-johnstone**
Checklist
-------------
- [x] Does each function have a comment to describe what it does ?
- [x] Are there comments throughout the code ?
- [x] Are the function or method names well chosen ?
- [x] Are variable names well chosen ?
- [x] List what testing has been done.
  - Tested with MLA ERP new sales order migration to qcode-6.

### CODE REVIEW

**Comment by nicky-johnstone** [comment]
Not sure if it should be changed here or later but I've observed an incorrect HTTP method type for information requests. I've created issue  #83 to demonstrate.

**Comment by bvw** [comment]
Does this break any old code ? Were you able to test it against old xml based responses.

**Comment by nicky-johnstone** [comment]
I know that it works with XML because the information to populate record values after entering a customer code in the sales order form is returned as XML.

I've gone back and tested it on the old sales_order_new code and there is a case that hadn't been considered; `return_next`.

The way I've built it is to expect JSON or XML which is fine for JSON because a POST will always return the JSON response. However, successful POSTs on the old transaction process would return a redirect rather than XML that specifies the action. I thought the solution would be as simple as;

```javascript
case "text/html; charset=utf-8":
            window.location.href = jqXHR.getResponseHeader('location');
            return;
```

but the browser interrupts and redirects instead of passing the response back to the javascript code. The response after redirecting is then passed back to the javascript code.

Need to think further on how to handle this case.

**Comment by nicky-johnstone** [comment]
Updated.

I tested the JSON sales_order_new using `formType add` and `addURL` rather than `submitURL` and it worked fine.

**Comment by bvw** [comment]
Could you list what testing has been done to make sure that any existing applications using this new version of dbForm will not break ?

dbForm is used on TLC projects as well.

**Comment by nicky-johnstone** [comment]
So far I've only tested it with `sales_order_new` in MLA ERP. Both the old version and the newly migrated version that I've been working on.

I'll look at where else dbForm is used in MLA ERP and test that it continues to work as expected for those forms.

**Comment by nicky-johnstone** [comment]
### MLA ERP Testing

* New mailing list
* Update mailing list
* Update sales account details
* Update customer details
* New GRN
* Update GRN
* Update home page preferences (order message)
* New journal voucher
* Update journal voucher
* Update financial system settings
* New price list
* Update price list
* Update product detail (non-stock)
* Update product details (stock)
* Update product details (stock) - supplier

There are many more uses of dbForm but the above have all functioned as expected so I'd imagine any others would too.

**Pull request merged**
